# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1', models.CharField(max_length=200)),
                ('Team2', models.CharField(max_length=200)),
                ('matchYear', models.CharField(max_length=20)),
                ('matchOrder', models.CharField(max_length=20)),
                ('gametype', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=20)),
                ('penalties', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
