# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=200)),
                ('CountryTeam', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='author',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gametype',
        ),
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AddField(
            model_name='match',
            name='HomeAway',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='matchID',
            field=models.IntegerField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='matchType',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
