# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20171228_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='CoinToss',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='goals1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='goals2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
