# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20171230_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchID2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
