# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_match_matchid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='countryID1',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='countryID2',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
